variable "network_subnet" {}
variable "rtorrent_rpc_host" {}
variable "nfs_general_path" {}
variable "nfs_torrent_path" {}
variable "nfs_adguard_path" {}
variable "adguard_host" {}
variable "adguard_catchall_host" {}
variable "traefik_api_key" {}
variable "github_user" {}
variable "github_pat" {}